import localFont from "next/font/local";
import "./globals.css";
import { NavigationHeader, NavigationFooter } from "@/components/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <div className="w-full grid grid-flow-col justify-between bg-pink-500 p-2">
          <h2 className="text-xl">Ascend Behavioral Health</h2>
          <div className="grid grid-flow-col bg-orange-500 gap-2">
            <div>Home</div>
            <div>Our Clinic</div>
            <div>Clinicians</div>
            <div>Services</div>
            <div>Contact Us</div>
          </div>
        </div> */}
        <NavigationHeader />
        {children}
        <NavigationFooter />
      </body>
    </html>
  );
}
